version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
